# Generated by Django 5.1.2 on 2024-10-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='desctiption',
            new_name='description',
        ),
    ]
